"""
Application Constants
Centralized constants to avoid magic numbers throughout the codebase
"""

# Audio/Media Constants
MAX_AUDIO_SIZE_BYTES = 10 * 1024 * 1024  # 10MB
MAX_AUDIO_SIZE_MB = 10
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_TTS_SAMPLE_RATE = 24000
MAX_SAMPLE_RATE = 48000
MIN_SAMPLE_RATE = 8000

# Timeout Constants (seconds)
DEFAULT_HTTP_TIMEOUT = 30
DEFAULT_CONNECT_TIMEOUT = 10
DEFAULT_LLM_TIMEOUT = 30
DEFAULT_STT_TIMEOUT = 15
DEFAULT_TTS_TIMEOUT = 20

# Pagination Constants
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
MIN_PAGE_SIZE = 1

# Rate Limiting Constants
DEFAULT_RATE_LIMIT = "10/minute"
CONVERSATION_RATE_LIMIT = "5/minute"
AUTH_LOGIN_RATE_LIMIT = "3/minute"
AUTH_REGISTER_RATE_LIMIT = "2/minute"
TUTORING_RATE_LIMIT = "10/minute"

# Cache Constants
DEFAULT_CACHE_TTL = 3600  # 1 hour
REDIS_CACHE_TTL = 3600  # 1 hour
CONVERSATION_CACHE_TTL = 3600  # 1 hour

# Buffer/Queue Constants
DEFAULT_WRITE_BUFFER_SIZE = 1000
DEFAULT_FLUSH_INTERVAL_MS = 100
MAX_MESSAGES_PER_SESSION = 500
MAX_SESSIONS = 1000

# Session Constants
SESSION_TTL_MINUTES = 120
DEFAULT_SESSION_TIMEOUT = 7200  # 2 hours in seconds

# Token Constants
DEFAULT_JWT_EXPIRATION_HOURS = 1
MAX_JWT_EXPIRATION_HOURS = 24
DEFAULT_REFRESH_EXPIRATION_HOURS = 168  # 7 days
MAX_REFRESH_EXPIRATION_HOURS = 720  # 30 days

# Retry Constants
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY = 1.0  # seconds
MAX_RETRY_DELAY = 60.0  # seconds

# Performance Constants
DEFAULT_WORKERS = 1
MAX_WORKERS = 32
DEFAULT_POOL_SIZE = 10
MAX_POOL_SIZE = 50
DEFAULT_MAX_OVERFLOW = 20

# Logging Constants
DEFAULT_LOG_LEVEL = "INFO"
MAX_LOG_FILE_SIZE_MB = 10
MAX_LOG_FILES = 10

# Security Constants
MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128
MIN_SECRET_KEY_LENGTH = 32

# CEFR Level Constants
CEFR_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2"]
DEFAULT_CEFR_LEVEL = "A1"

# Skill Constants
MAX_SKILLS_PER_REQUEST = 50
DEFAULT_SKILL_LIMIT = 189

# Analysis Constants
DEFAULT_ANALYSIS_WINDOW_DAYS = 90
DEFAULT_ATTENTION_WINDOW = 30
MIN_ATTEMPTS_FOR_PATTERN = 5
ERROR_RATE_THRESHOLD_PROBLEMATIC = 0.5  # 50%
ERROR_RATE_THRESHOLD_MASTERED = 0.2  # 20%
